// The owned conversation loop must drive a reply for EVERY kind of answer —
// spoken (either interactivity mode) or typed. LiveAvatar's own pipelines
// generate but never voice a reply, so any path that hands them the turn is a
// silent dead-end: the avatar simply never responds (2026-07-14 field report).

import { describe, expect, it, vi, beforeEach } from "vitest";
import { act, renderHook, waitFor } from "@testing-library/react";

const {
  invokeMock,
  SessionEvent,
  AgentEventsEnum,
  SessionInteractivityMode,
  SessionState,
  VoiceChatState,
  MockLiveAvatarSession,
} = vi.hoisted(() => {
  const SessionEvent = {
    SESSION_STREAM_READY: "session.stream_ready",
    SESSION_STATE_CHANGED: "session.state_changed",
    SESSION_DISCONNECTED: "session.disconnected",
  } as const;
  const AgentEventsEnum = {
    SESSION_STOPPED: "agent.session_stopped",
    AVATAR_SPEAK_STARTED: "agent.avatar_speak_started",
    AVATAR_SPEAK_ENDED: "agent.avatar_speak_ended",
    USER_TRANSCRIPTION: "agent.user_transcription",
    USER_TRANSCRIPTION_CHUNK: "agent.user_transcription_chunk",
  } as const;
  const SessionInteractivityMode = {
    PUSH_TO_TALK: "PUSH_TO_TALK",
    CONVERSATIONAL: "CONVERSATIONAL",
  } as const;
  const SessionState = { CONNECTED: "CONNECTED" } as const;
  const VoiceChatState = { ACTIVE: "ACTIVE", INACTIVE: "INACTIVE" } as const;

  class MockLiveAvatarSession {
    static instances: MockLiveAvatarSession[] = [];
    handlers = new Map<string, Array<(arg?: unknown) => void>>();
    repeat = vi.fn();
    message = vi.fn();
    interrupt = vi.fn();
    attach = vi.fn();
    startListening = vi.fn();
    stopListening = vi.fn();
    removeAllListeners = vi.fn();
    stop = vi.fn(async () => undefined);
    start = vi.fn(async () => undefined);
    voiceChat = {
      state: VoiceChatState.INACTIVE as string,
      isMuted: true,
      start: vi.fn(async () => {
        this.voiceChat.state = VoiceChatState.ACTIVE;
      }),
      mute: vi.fn(async () => {
        this.voiceChat.isMuted = true;
      }),
      unmute: vi.fn(async () => {
        this.voiceChat.isMuted = false;
      }),
      startPushToTalk: vi.fn(async () => undefined),
      stopPushToTalk: vi.fn(async () => undefined),
    };

    constructor(
      public token: string,
      public opts: unknown,
    ) {
      MockLiveAvatarSession.instances.push(this);
    }
    on(event: string, cb: (arg?: unknown) => void) {
      const list = this.handlers.get(event) ?? [];
      list.push(cb);
      this.handlers.set(event, list);
    }
    emit(event: string, arg?: unknown) {
      for (const cb of this.handlers.get(event) ?? []) cb(arg);
    }
  }

  return {
    invokeMock: vi.fn(),
    SessionEvent,
    AgentEventsEnum,
    SessionInteractivityMode,
    SessionState,
    VoiceChatState,
    MockLiveAvatarSession,
  };
});

vi.mock("@/lib/supabase/client", () => ({
  getSupabase: () => ({ functions: { invoke: invokeMock } }),
}));
vi.mock("@/lib/data/statements", () => ({
  listStatements: async () => [],
}));

vi.mock("@heygen/liveavatar-web-sdk", () => ({
  LiveAvatarSession: MockLiveAvatarSession,
  SessionEvent,
  AgentEventsEnum,
  SessionInteractivityMode,
  SessionState,
  VoiceChatState,
}));

import { useLiveAvatarPractice } from "./useLiveAvatarPractice";

function mockBackend(interactivity: "PUSH_TO_TALK" | "CONVERSATIONAL") {
  invokeMock.mockImplementation(async (fn: string) => {
    if (fn === "advocate-avatar-session") {
      return { data: { token: "tok", practiceCapSec: 120, interactivity }, error: null };
    }
    if (fn === "advocate-agent") {
      return { data: { text: "A reply line." }, error: null };
    }
    return { data: null, error: new Error(`unexpected fn ${fn}`) };
  });
}

async function connectedHook() {
  const rendered = renderHook(() => useLiveAvatarPractice());
  await act(async () => {
    expect(await rendered.result.current.connect()).toBe("open");
  });
  const session = MockLiveAvatarSession.instances.at(-1);
  if (!session) throw new Error("no session constructed");
  act(() => session.emit(SessionEvent.SESSION_STATE_CHANGED, SessionState.CONNECTED));
  // The opener is generated by us and spoken verbatim.
  await waitFor(() => expect(session.repeat).toHaveBeenCalledTimes(1));
  return { rendered, session };
}

function defenseTurnCalls() {
  return invokeMock.mock.calls.filter(
    (c) => c[0] === "advocate-agent" && c[1]?.body?.agent === "defense_turn",
  );
}

beforeEach(() => {
  invokeMock.mockReset();
  MockLiveAvatarSession.instances = [];
  Object.defineProperty(navigator, "mediaDevices", {
    configurable: true,
    value: { getUserMedia: vi.fn(async () => ({ getTracks: () => [] })) },
  });
});

describe("useLiveAvatarPractice owned loop", () => {
  it("drives a spoken reply after an answer even in PUSH_TO_TALK mode", async () => {
    mockBackend("PUSH_TO_TALK");
    const { rendered, session } = await connectedHook();

    await act(async () => {
      await rendered.result.current.startAnswer();
    });
    act(() => session.emit(AgentEventsEnum.USER_TRANSCRIPTION, { text: "It happened at night." }));
    await act(async () => {
      await rendered.result.current.endAnswer();
    });

    await waitFor(() => expect(session.repeat).toHaveBeenCalledTimes(2));
    const turns = defenseTurnCalls().at(-1)?.[1].body.input.turns;
    expect(turns).toContainEqual({ role: "user", text: "It happened at night." });
  });

  it("routes typed answers through the owned loop, never session.message()", async () => {
    mockBackend("CONVERSATIONAL");
    const { rendered, session } = await connectedHook();

    act(() => {
      rendered.result.current.sendText("I want to practice saying it out loud.");
    });

    await waitFor(() => expect(session.repeat).toHaveBeenCalledTimes(2));
    expect(session.repeat).toHaveBeenLastCalledWith("A reply line.");
    expect(session.message).not.toHaveBeenCalled();
    const turns = defenseTurnCalls().at(-1)?.[1].body.input.turns;
    expect(turns).toContainEqual({
      role: "user",
      text: "I want to practice saying it out loud.",
    });
  });

  it("still speaks when an answer captured no words — never a silent dead-end", async () => {
    mockBackend("CONVERSATIONAL");
    const { rendered, session } = await connectedHook();

    await act(async () => {
      await rendered.result.current.startAnswer();
    });
    await act(async () => {
      await rendered.result.current.endAnswer(); // no transcription arrived
    });

    await waitFor(() => expect(session.repeat).toHaveBeenCalledTimes(2));
  });
});
