/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotebooksRouteImport } from './routes/notebooks'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ExpertRouteImport } from './routes/expert'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BreakRouteImport } from './routes/break'
import { Route as BeginRouteImport } from './routes/begin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalRecordsRouteImport } from './routes/professional.records'
import { Route as ProfessionalKnowledgeRouteImport } from './routes/professional.knowledge'
import { Route as ProfessionalClientsRouteImport } from './routes/professional.clients'
import { Route as NotebooksSlugRouteImport } from './routes/notebooks.$slug'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksRoute = NotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertRoute = ExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakRoute = BreakRouteImport.update({
  id: '/break',
  path: '/break',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginRoute = BeginRouteImport.update({
  id: '/begin',
  path: '/begin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRecordsRoute = ProfessionalRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalKnowledgeRoute = ProfessionalKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalClientsRoute = ProfessionalClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProfessionalRoute,
} as any)
const NotebooksSlugRoute = NotebooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NotebooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/begin': typeof BeginRoute
  '/break': typeof BreakRoute
  '/dev': typeof DevRoute
  '/enter': typeof EnterRoute
  '/expert': typeof ExpertRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/judges': typeof JudgesRoute
  '/notebooks': typeof NotebooksRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/team': typeof TeamRoute
  '/notebooks/$slug': typeof NotebooksSlugRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
  '/professional/records': typeof ProfessionalRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/begin': typeof BeginRoute
  '/break': typeof BreakRoute
  '/dev': typeof DevRoute
  '/enter': typeof EnterRoute
  '/expert': typeof ExpertRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/judges': typeof JudgesRoute
  '/notebooks': typeof NotebooksRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/team': typeof TeamRoute
  '/notebooks/$slug': typeof NotebooksSlugRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
  '/professional/records': typeof ProfessionalRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/begin': typeof BeginRoute
  '/break': typeof BreakRoute
  '/dev': typeof DevRoute
  '/enter': typeof EnterRoute
  '/expert': typeof ExpertRoute
  '/guide': typeof GuideRoute
  '/home': typeof HomeRoute
  '/judges': typeof JudgesRoute
  '/notebooks': typeof NotebooksRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/team': typeof TeamRoute
  '/notebooks/$slug': typeof NotebooksSlugRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
  '/professional/records': typeof ProfessionalRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/begin'
    | '/break'
    | '/dev'
    | '/enter'
    | '/expert'
    | '/guide'
    | '/home'
    | '/judges'
    | '/notebooks'
    | '/onboarding'
    | '/plan'
    | '/privacy'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/sources'
    | '/team'
    | '/notebooks/$slug'
    | '/professional/clients'
    | '/professional/knowledge'
    | '/professional/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/begin'
    | '/break'
    | '/dev'
    | '/enter'
    | '/expert'
    | '/guide'
    | '/home'
    | '/judges'
    | '/notebooks'
    | '/onboarding'
    | '/plan'
    | '/privacy'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/sources'
    | '/team'
    | '/notebooks/$slug'
    | '/professional/clients'
    | '/professional/knowledge'
    | '/professional/records'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/begin'
    | '/break'
    | '/dev'
    | '/enter'
    | '/expert'
    | '/guide'
    | '/home'
    | '/judges'
    | '/notebooks'
    | '/onboarding'
    | '/plan'
    | '/privacy'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/sources'
    | '/team'
    | '/notebooks/$slug'
    | '/professional/clients'
    | '/professional/knowledge'
    | '/professional/records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BeginRoute: typeof BeginRoute
  BreakRoute: typeof BreakRoute
  DevRoute: typeof DevRoute
  EnterRoute: typeof EnterRoute
  ExpertRoute: typeof ExpertRoute
  GuideRoute: typeof GuideRoute
  HomeRoute: typeof HomeRoute
  JudgesRoute: typeof JudgesRoute
  NotebooksRoute: typeof NotebooksRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks': {
      id: '/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof NotebooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert': {
      id: '/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ExpertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break': {
      id: '/break'
      path: '/break'
      fullPath: '/break'
      preLoaderRoute: typeof BreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/begin': {
      id: '/begin'
      path: '/begin'
      fullPath: '/begin'
      preLoaderRoute: typeof BeginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/records': {
      id: '/professional/records'
      path: '/records'
      fullPath: '/professional/records'
      preLoaderRoute: typeof ProfessionalRecordsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/knowledge': {
      id: '/professional/knowledge'
      path: '/knowledge'
      fullPath: '/professional/knowledge'
      preLoaderRoute: typeof ProfessionalKnowledgeRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/clients': {
      id: '/professional/clients'
      path: '/clients'
      fullPath: '/professional/clients'
      preLoaderRoute: typeof ProfessionalClientsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/notebooks/$slug': {
      id: '/notebooks/$slug'
      path: '/$slug'
      fullPath: '/notebooks/$slug'
      preLoaderRoute: typeof NotebooksSlugRouteImport
      parentRoute: typeof NotebooksRoute
    }
  }
}

interface NotebooksRouteChildren {
  NotebooksSlugRoute: typeof NotebooksSlugRoute
}

const NotebooksRouteChildren: NotebooksRouteChildren = {
  NotebooksSlugRoute: NotebooksSlugRoute,
}

const NotebooksRouteWithChildren = NotebooksRoute._addFileChildren(
  NotebooksRouteChildren,
)

interface ProfessionalRouteChildren {
  ProfessionalClientsRoute: typeof ProfessionalClientsRoute
  ProfessionalKnowledgeRoute: typeof ProfessionalKnowledgeRoute
  ProfessionalRecordsRoute: typeof ProfessionalRecordsRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalClientsRoute: ProfessionalClientsRoute,
  ProfessionalKnowledgeRoute: ProfessionalKnowledgeRoute,
  ProfessionalRecordsRoute: ProfessionalRecordsRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BeginRoute: BeginRoute,
  BreakRoute: BreakRoute,
  DevRoute: DevRoute,
  EnterRoute: EnterRoute,
  ExpertRoute: ExpertRoute,
  GuideRoute: GuideRoute,
  HomeRoute: HomeRoute,
  JudgesRoute: JudgesRoute,
  NotebooksRoute: NotebooksRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
