/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EnterRouteImport } from './routes/enter'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalKnowledgeRouteImport } from './routes/professional.knowledge'
import { Route as ProfessionalClientsRouteImport } from './routes/professional.clients'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterRoute = EnterRouteImport.update({
  id: '/enter',
  path: '/enter',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalKnowledgeRoute = ProfessionalKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalClientsRoute = ProfessionalClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProfessionalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/enter': typeof EnterRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/enter': typeof EnterRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/enter': typeof EnterRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/plan': typeof PlanRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/professional/clients': typeof ProfessionalClientsRoute
  '/professional/knowledge': typeof ProfessionalKnowledgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/enter'
    | '/home'
    | '/onboarding'
    | '/plan'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/team'
    | '/professional/clients'
    | '/professional/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/enter'
    | '/home'
    | '/onboarding'
    | '/plan'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/team'
    | '/professional/clients'
    | '/professional/knowledge'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/enter'
    | '/home'
    | '/onboarding'
    | '/plan'
    | '/professional'
    | '/resources'
    | '/session'
    | '/settings'
    | '/team'
    | '/professional/clients'
    | '/professional/knowledge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EnterRoute: typeof EnterRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  PlanRoute: typeof PlanRoute
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter': {
      id: '/enter'
      path: '/enter'
      fullPath: '/enter'
      preLoaderRoute: typeof EnterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/knowledge': {
      id: '/professional/knowledge'
      path: '/knowledge'
      fullPath: '/professional/knowledge'
      preLoaderRoute: typeof ProfessionalKnowledgeRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/clients': {
      id: '/professional/clients'
      path: '/clients'
      fullPath: '/professional/clients'
      preLoaderRoute: typeof ProfessionalClientsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
  }
}

interface ProfessionalRouteChildren {
  ProfessionalClientsRoute: typeof ProfessionalClientsRoute
  ProfessionalKnowledgeRoute: typeof ProfessionalKnowledgeRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalClientsRoute: ProfessionalClientsRoute,
  ProfessionalKnowledgeRoute: ProfessionalKnowledgeRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EnterRoute: EnterRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  PlanRoute: PlanRoute,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
